version: "3"

services:
  frontend:
    networks:
      - frontend
    restart: always
    build:
      context: ./
      args:
        VITE_API_HOST: api.shamtool.com

# This network has to be created by yourself, compose won't do it for you.
networks:
  frontend:
    external: true
