name: Build and deploy to GH-pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the alpha branch
  push:
    branches: [ main, alpha ]
  pull_request:
    branches: [ main, alpha ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build and push to gh-pages
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello!
        
      - name: Install and Build # This example project is built using npm and outputs the result to the 'build-gh' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          pnpm ci
          pnpm run build:gh

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build-gh # The folder the action should deploy.
          
